-- MySQL Script generated by MySQL Workbench
-- sø. 04. okt. 2020 kl. 19.18 +0200
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trax
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `trax` ;

-- -----------------------------------------------------
-- Schema trax
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trax` ;
USE `trax` ;

-- -----------------------------------------------------
-- Table `trax`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trax`.`User` ;

CREATE TABLE IF NOT EXISTS `trax`.`User` (
  `idUser` VARCHAR(40) NOT NULL DEFAULT 'uuid()',
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NULL,
  `dateCreated` DATETIME NULL,
  `authmethod` VARCHAR(45) NULL,
  `lastLogin` DATETIME NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trax`.`Team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trax`.`Team` ;

CREATE TABLE IF NOT EXISTS `trax`.`Team` (
  `idTeam` VARCHAR(40) NOT NULL,
  `teamName` VARCHAR(45) NOT NULL,
  `manager` VARCHAR(45) NOT NULL,
  `dateCreated` DATETIME NOT NULL,
  PRIMARY KEY (`idTeam`),
  UNIQUE INDEX `idTeam_UNIQUE` (`idTeam` ASC) VISIBLE,
  INDEX `fk_Team_User_idx` (`manager` ASC) VISIBLE,
  CONSTRAINT `fk_Team_User`
    FOREIGN KEY (`manager`)
    REFERENCES `trax`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trax`.`Match`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trax`.`Match` ;

CREATE TABLE IF NOT EXISTS `trax`.`Match` (
  `idMatch` VARCHAR(40) NOT NULL,
  `homeTeam` VARCHAR(45) NOT NULL,
  `awayTeam` VARCHAR(45) NOT NULL,
  `homeTeamGoals` INT NOT NULL,
  `awayTeamGoals` INT NOT NULL,
  `matchDate` DATETIME NOT NULL,
  PRIMARY KEY (`idMatch`),
  UNIQUE INDEX `idMatch_UNIQUE` (`idMatch` ASC) VISIBLE,
  INDEX `fk_hometeam_idx` (`homeTeam` ASC) VISIBLE,
  INDEX `fk_awayteam_idx` (`awayTeam` ASC) VISIBLE,
  CONSTRAINT `fk_hometeam`
    FOREIGN KEY (`homeTeam`)
    REFERENCES `trax`.`Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_awayteam`
    FOREIGN KEY (`awayTeam`)
    REFERENCES `trax`.`Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
